name: Test Snapshot

# manual workflow dispatch, we require needed versions
on: [workflow_dispatch]

# stash needed inputs to env
# we use trusted actions so it's ok to share env with all
env:
  JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}

# one main build job which build and tags a release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # basic build stuff setup
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.36.0

    # sanity checks
    - name: Sanity Check
      uses: jvalkeal/build-zoo-handler@main
      with:
        ensure-commands: |
          jfrog
          mvn

    # configure jfrog targets
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-resolve=spring \
          --repo-resolve-releases=libs-private-release \
          --repo-resolve-snapshots=libs-private-snapshot \
          --server-id-deploy=spring \
          --repo-deploy-releases=libs-private-release \
          --repo-deploy-snapshots=libs-private-snapshot

    # build and publish
    - name: Build and Publish
      run: |
        jfrog rt mvn -U -B clean install
