name: Test Release

# manual workflow dispatch, we require needed versions
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        default: '0.0.0'
      bootVersion:
        description: 'Boot Version'
        required: true
        default: '2.3.1.RELEASE'
      test1Version:
        description: 'Test1 Version'
        required: true
        default: '0.0.0'
      test2Version:
        description: 'Test1 Version'
        required: true
        default: '0.0.0'

# stash needed inputs to env
# we use trusted actions so it's ok to share env with all
env:
  RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
  BOOT_VERSION: ${{ github.event.inputs.bootVersion }}
  TEST1_VERSION: ${{ github.event.inputs.test1Version }}
  TEST2_VERSION: ${{ github.event.inputs.test2Version }}
  JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}

# one main build job which build and tags a release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # basic build stuff setup
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.36.0

    # sanity checks
    - name: Sanity Check
      uses: jvalkeal/build-zoo-handler@main
      with:
        ensure-commands: |
          jfrog
          mvn
        ensure-env: |
          RELEASE_VERSION
          TEST1_VERSION
          TEST2_VERSION

    # configure jfrog targets
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-resolve=spring \
          --repo-resolve-releases=libs-private-release \
          --repo-resolve-snapshots=libs-private-snapshot \
          --server-id-deploy=spring \
          --repo-deploy-releases=libs-private-release \
          --repo-deploy-snapshots=libs-private-snapshot

    # massage poms
    - name: Configure Release Versions
      run: |
        mvn versions:update-parent -DgenerateBackupPoms=false -DparentVersion=[$BOOT_VERSION]
        mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION
        mvn versions:set-property -DgenerateBackupPoms=false -Dproperty=test1.version -DnewVersion=$TEST1_VERSION
        mvn versions:set-property -DgenerateBackupPoms=false -Dproperty=test2.version -DnewVersion=$TEST2_VERSION

    # build and publish
    - name: Build and Publish
      run: |
        jfrog rt mvn -U -B clean install

    # tag release
    - name: Tag Release
      uses: jvalkeal/build-zoo-handler@main
      with:
        tag-release-username: 'Spring Buildmaster'
        tag-release-useremail: 'buildmaster@springframework.org'
        tag-release-branch: ${{ github.event.inputs.releaseVersion }}
