name: CITest 

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [1.8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Tar Build Logs
      if: ${{ failure() }}
      run: |
        tar -zc --ignore-failed-read --file build/gradlelogs.tar.gz build/test-results
    - name: Upload Build Logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: buildlogs
        path: build/gradlelogs.tar.gz
