name: Release 1.0.x

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: false
  repository_dispatch:
    types: [build-zoo-handler-release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # base setup
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - uses: jfrog/setup-jfrog-cli@v1
      with:
        version: 1.36.0
      env:
        JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SECRET_SPRING }}
    - name: Configure JFrog Cli
      run: |
        jfrog rt mvnc \
          --server-id-resolve=spring \
          --server-id-deploy=spring \
          --repo-resolve-releases=libs-spring-dataflow-private-release \
          --repo-resolve-snapshots=libs-spring-dataflow-private-snapshot \
          --repo-deploy-releases=libs-spring-dataflow-private-release \
          --repo-deploy-snapshots=libs-spring-dataflow-private-snapshot \

    # zoo extract and ensure
    - name: Extract Zoo Context Properties
      uses: jvalkeal/build-zoo-handler@main
      with:
        dispatch-handler-extract-context-properties: true

    # build
    - name: Build and Publish
      id: build
      run: |
        jfrog rt mvn build-helper:parse-version versions:set \
          -DprocessAllModules=false -DgenerateBackupPoms=false \
          -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'
        jfrog rt mvn -U -B clean install
        echo ::set-env name=BUILD_ZOO_HANDLER_atest4_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

    # zoo tag
    - name: Tag Release
      uses: jvalkeal/build-zoo-handler@main
      with:
        tag-release-branch: ${{ env.BUILD_ZOO_HANDLER_atest1_version }}
        tag-release-tag: ${{ env.BUILD_ZOO_HANDLER_atest1_version }}
        tag-release-tag-prefix: v

    # zoo success
    - name: Notify Build Success Zoo Handler Controller
      uses: jvalkeal/build-zoo-handler@main
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-owner: jvalkeal
        dispatch-handler-repo: atest1
        dispatch-handler-workflow: train-release-13x.yml
        # dispatch-handler-workflow: 123
        # dispatch-handler-workflow: Release Train 1.3.x
        # dispatch-handler-event-type: build-zoo-handler-control-release
        dispatch-handler-client-payload-data: >
          {
            "event": "release-succeed"
          }

    # zoo failure
    - name: Notify Build Failure Zoo Handler Controller
      if: ${{ failure() }}
      uses: jvalkeal/build-zoo-handler@main
      with:
        dispatch-handler-token: ${{ secrets.REPO_ACCESS_TOKEN }}
        dispatch-handler-owner: jvalkeal
        dispatch-handler-repo: atest1
        dispatch-handler-workflow: train-release-13x.yml
        # dispatch-handler-workflow: 123
        # dispatch-handler-event-type: build-zoo-handler-control-release
        dispatch-handler-client-payload-data: >
          {
            "event": "release-failed"
          }
